[build]
  publish = "dist/login-website/browser"  # ระบุโฟลเดอร์ที่ต้องการเผยแพร่
  command = "ng build --configuration production"  # คำสั่งในการ build โปรเจค

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
